brew "bat"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "glab"
brew "git"
brew "git-delta"
brew "jq"
brew "mise"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"

# PHP build dependencies for mise (vfox-php compiles PHP from source and
# installs Composer as bin/composer alongside it).
brew "autoconf"
brew "bison"
brew "re2c"
brew "pkg-config"
brew "libxml2"
brew "openssl@3"
brew "icu4c"
brew "zlib"
brew "libzip"
brew "oniguruma"
brew "freetype"
brew "gd"
brew "libiconv"
brew "jpeg"
brew "libpng"
brew "webp"
brew "gmp"
brew "libsodium"
brew "readline"
brew "bzip2"

cask "ghostty"
cask "font-jetbrains-mono-nerd-font"
