"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$fill\
$nodejs$python$golang$rust$java$php$c\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[git_state]
style = "bold red"

[cmd_duration]
min_time = 2000
format = "[ $duration]($style) "
style = "yellow"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[java]
symbol = " "
format = "[$symbol($version )]($style)"

[php]
symbol = " "
format = "[$symbol($version )]($style)"

[c]
symbol = " "
format = "[$symbol($version(-$name) )]($style)"

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
only_with_files = true
